ktor:
  application:
    modules:
      - appdev.studdybuddy.ApplicationKt.module
  deployment:
    port: 5431
postgres:
  url: "jdbc:postgresql://localhost:5432/appdevdb"
  user: "admin"
  password: ""